[package]
name = "git-count-commits"
version = "0.1.0"
authors = ["shio-yaamaa <shio.yama520@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
